language: android
android:
   components:
   - platform-tools
   - android-21
   - build-tools-21.1.2
   - extra

jdk: oraclejdk7

notifications:
  email: false
  hipchat:
    rooms:
      secure: coAicb4gDk5m03J7BZLE7AtHXql1nFg4Uxv5jtGlUGLV9srNZ8X3SNZK+CnMywcKtMJlvJMi573TdrvUna4VP1XQkIEsZtL+xRvNkXszTjWmOlUW4EXTUZJoeywLhOAbtVYf0aaVtOCoFvxovamG7rNL+ylxBuxTcjcbHJywpHM=
    room:
      secure: qFah5+8qh68F7uKueL9mB7BbrxDwIu8ca5Edpf8IkJG2Nh0VbGXO3DD9Dxsvdts0SJhkNXS+aLavQcZuxT+olKpp5MX1RdhAjvX0EmDQQ9w7fKFonzgGI+2pBCG80HRG/KrL+txPRRuhNPT7VCKxNtPh7OQf1lIQMIrPsqo5aPk=

before_install:
- sudo apt-get update -qq
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm
  ia32-libs ia32-libs-multiarch > /dev/null; fi

- echo "sonatypeRepo=https://oss.sonatype.org/content/repositories/snapshots/" > ~/.gradle/gradle.properties
- echo "sonatypeSnapshotRepo=https://oss.sonatype.org/content/repositories/snapshots/" >> ~/.gradle/gradle.properties
- echo "sonatypeUsername=xxx" >> ~/.gradle/gradle.properties
- echo "sonatypePassword=xxx" >> ~/.gradle/gradle.properties
